# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Dependencies
      run: |
        npx npm-force-resolutions
        npm install
        npm install -g @angular/cli
    - name: Build
      run: ng build --prod
      env:
        CI: true
  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: FTP deployment
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: FTP_SERVER
          # ftp username
          username: FTP_USER
          # ftp password
          password: FTP_PASSWORD
          # Folder to upload from, must end with trailing slash /
          local-dir: ./dist/ecordel-web/
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: true
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: .*
